# Generated by Django 5.2.6 on 2025-11-17 10:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='nom_abonnement',
            field=models.CharField(choices=[('classique', 'CLassique'), ('premium', 'Premium'), ('vip', 'VIP')], default='classique', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
