# Generated by Django 5.2.8 on 2025-11-18 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_subscription_nom_abonnement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='nom_abonnement',
            field=models.CharField(choices=[('classique', 'Classique'), ('premium', 'Premium'), ('vip', 'VIP')], default='classique', max_length=20),
        ),
    ]
